### ISSUE TITLE
which type of ANS does brunsli use?

### ISSUE THREAD

**Issue by xiaoxiongli** [google/brunsli#101]
Dear all, 

I read the brunsli's ANS related code, such as AddCode or PutSymbol..., As you know, the ANS has a lot of variant, but I can not figure out which type of ANS the brunsli is using. 

Could you please help me to understand the brunsli's ANS algorithm?

![image](https://user-images.githubusercontent.com/13975044/87425002-88ca7480-c60f-11ea-9ef1-35c52e3df314.png)

**Comment by eustas** [comment]
Hello.

It is somewhere in-between rANS and tANS.

First of all, let's drop `BRUNSLI_USE_MULT_BY_RECIPROCAL`, it is just an optimisation. What's left?:
```
uint32_t PutSymbol(const ANSEncSymbolInfo t, uint8_t* nbits) {
  // By default, no normalisation is required.
  uint32_t bits = 0;
  *nbits = 0;
  // Check if normalisation is required...
  // rANS wiki: inverse of: if(x < (1 << 16)) x = (x << 16) + read16bits()
  if ((state_ >> (32 - BRUNSLI_ANS_LOG_TAB_SIZE)) >= t.freq_) {
    // Get normalisation output and normalise.
    bits = state_ & 0xffff;
    state_ >>= 16;
    *nbits = 16;
  }
  // rANS wiki: C(x,s) = (floor(x / f[s]) << n) + (x % f[s]) + CDF[s]
  state_ = ((state_ / t.freq_) << BRUNSLI_ANS_LOG_TAB_SIZE) + (state_ % t.freq_) + t.start_;
  return bits;
}
```

**Comment by eustas** [comment]
Hope it helps. If you have more questions, feel free to reopen the issue.

**Comment by xiaoxiongli** [comment]
Dear @eustas, 

thank you very much for you reply. ^_^ 

And I feel confused about below code:
  // rANS wiki: inverse of: if(x < (1 << 16)) x = (x << 16) + read16bits()
  if ((state_ >> (32 - BRUNSLI_ANS_LOG_TAB_SIZE)) >= t.freq_) {
    // Get normalisation output and normalise.
    bits = state_ & 0xffff;
    state_ >>= 16;
    *nbits = 16;
  }

the rANS wiki said that,  
![image](https://user-images.githubusercontent.com/13975044/87499160-1d72b800-c68c-11ea-8e68-d287247a3853.png)
and in brunsli's code it seems re-normalize the x( or state_) to [0, t.freq_<<8]?  8 is (32 - BRUNSLI_ANS_LOG_TAB_SIZE) - 16 ,  am I right?  if I am wrong, how to understand this line: "if ((state_ >> (32 - BRUNSLI_ANS_LOG_TAB_SIZE)) >= t.freq_)"
