### ISSUE TITLE
Is brunsli's ANS using static probability distributions?

### ISSUE THREAD

**Issue by xiaoxiongli** [google/brunsli#102]
Dear All:
    In the brunsli's code, it seems run like below:
    1) context modeling, let's say we get 27 x 9 bins(histogram) for example.
    2) cluster the histogram(27x9) to reduce the context bin's count, for example after cluster, 27x9 reduce to 5.
    3) build 5 ANS table.
    4) during encode, get a context value and map it to one of the 5 ANS table then perform ANS encode(PutSymbol).

it seems that we need know all of the DCT coefficients, and then we perform encode with ANS,  in other words, when ANS table is built,  for each symbol(18 in brunsli) the probability never changed,  it use static probability distributions. am i right?

As you know,  in dropbox's lepton there is a arithmetic encoder to encode the residual of the DCT coefficents,  the arithmetic encoder can adjust the  probability internally, see below red line:

![image](https://user-images.githubusercontent.com/13975044/87622845-93dbec80-c756-11ea-97b9-54e868f37b68.png)
so, in this way, during lepton's arithmetic encoding, the probability is dynamic adjust locally.

my concern is since ANS is using static probability distributions instead of dynamic adjust it locally, the finally compression ratio maybe will get worse,  am I right?  if it is true, could we adjust probability dynamically in brunsli's ANS to improve the compression ratio?

**Comment by eustas** [comment]
Brunsli uses ANS for decoding "outline" of the value. For many things that constitute the resulting DCT values Brunsli uses arithmetic code (see https://github.com/google/brunsli/blob/master/c/dec/arith_decode.h)

**Comment by xiaoxiongli** [comment]
Dear @eustas ,
       what's the meaning of "outline" of the value? 
       In brunsli's code,  it seems use ANS to encode the residual of the DCT coefficents and use Arithmetic encoder to encode some flags(usually 1 bit).
