### ISSUE TITLE
brunsli.dev cannot decode JPEG compressed by recent cbrunsli.exe builds (CMake build 78 and newer)

### ISSUE THREAD

**Issue by Mithgol** [google/brunsli#106]
Looks like an interoperability problem. Steps to reproduce:

**Step 1.** We'll use the following “why is the Internet like this” meme (quoted from “Oshi no Ko” manga) as an example JPEG:

![(why is the Internet like this)](https://user-images.githubusercontent.com/1088720/89469220-ae1b5000-d781-11ea-890d-44a2ba427ab5.jpg)

Download it.

**Step 2.** Let's confirm that the problem is (relatively) recent.

Visit the “[Actions](https://github.com/google/brunsli/actions)” section and open the page of [CMake build 77](https://github.com/google/brunsli/actions/runs/168834558). Its “windows” artifact looks like that:

[windows.zip](https://github.com/google/brunsli/files/5031534/windows.zip)

Unpack `cbrunsli.exe` from this ZIP to the subdirectory where the meme from step 1 resides.

Run the command `cbrunsli.exe "why is the Internet like this.jpg"` in that subdirectory.

The following `why is the Internet like this.jpg.brn` file (55141 bytes long) is generated (see in the attached ZIP):

[why is the Internet like this 1.zip](https://github.com/google/brunsli/files/5031546/why.is.the.Internet.like.this.1.zip)

Dragging and dropping that file to https://brunsli.dev/ generates a decoded picture:

![(screenshot)](https://user-images.githubusercontent.com/1088720/89470565-c3de4480-d784-11ea-927f-67ba1e53f486.png)

**Step 3.** Let's confirm where the problem started.

Visit the “[Actions](https://github.com/google/brunsli/actions)” section and open the page of the next CMake build: [CMake build 78](https://github.com/google/brunsli/actions/runs/175839796). Its “windows” artifact looks like that:

[windows78.zip](https://github.com/google/brunsli/files/5031568/windows78.zip)

Unpack `cbrunsli.exe` from this ZIP to the subdirectory where the meme from step 1 resides (replacing `cbrunsli.exe` that was unpacked by the previous step).

Run the command `cbrunsli.exe "why is the Internet like this.jpg"` in that subdirectory.

The following `why is the Internet like this.jpg.brn` file (55483 bytes long) is generated (see in the attached ZIP):

[why is the Internet like this 2.zip](https://github.com/google/brunsli/files/5031574/why.is.the.Internet.like.this.2.zip)

Its difference from the result of step 2 is made obvious by its different filesize.

Dragging and dropping that file to https://brunsli.dev/ generates an error message (“Reconstuction failed”):

![(screenshot)](https://user-images.githubusercontent.com/1088720/89471426-ca6dbb80-d786-11ea-841c-ed318a6e2abf.png)

**Step 4.** Let's confirm that the problem persists.

Visit the “[Actions](https://github.com/google/brunsli/actions)” section and open the page of the latest CMake build: [CMake build 85](https://github.com/google/brunsli/actions/runs/193203405). Its “windows” artifact looks like that:

[windows85.zip](https://github.com/google/brunsli/files/5031599/windows85.zip)

Unpack `cbrunsli.exe` from this ZIP to the subdirectory where the meme from step 1 resides (replacing `cbrunsli.exe` that was unpacked by the previous step).

Run the command `cbrunsli.exe "why is the Internet like this.jpg"` in that subdirectory.

Confirm that the generated file `why is the Internet like this.jpg.brn` has the same filesize (55483 bytes) as the file generated by step 3 and that files' contents do not differ.

Dragging and dropping that file to https://brunsli.dev/ generates the same error message (“Reconstuction failed”).

(However, newer `dbrunsli.exe` correctly decodes files generated by the corresponding newer `cbrunsli.exe`.

Does that mean that https://brunsli.dev/ needs an update?)

**Comment by eustas** [comment]
Hello. Thanks for the report.
Will update site soon...

**Comment by Mithgol** [comment]
Is it fine for the newer cbrunsli to generate a slightly larger compressed file? (I know the difference is less than 1%, but…)

**Comment by eustas** [comment]
Sorry for the long wait. Should work now.

As for size regression - yes, that might be a side-effect. On some (hopefully most) files it became better, on some it is worse...
