### ISSUE TITLE
CI: Add tests

### ISSUE THREAD

**Issue by EwoutH** [google/brunsli#113]
Currently all the CI jobs [can't find](https://github.com/google/brunsli/runs/1761966175?check_suite_focus=true#step:5:1) don't run the ctests, because no tests are found:
```
Run cd out && ctest -j 2
Test project /home/runner/work/brunsli/brunsli/out
No tests were found!!!
```

**Comment by eustas** [comment]
Tests haven't been added to cmake file yet...

**Comment by eustas** [comment]
Done (excluding Android and WASM builds)
