### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by uilianries** [google/brunsli#134]
Hello all!

I see your last release (1.0) is from 2019: https://github.com/google/brunsli/releases/tag/v0.1

Are you considering a new release, or this project follows bleeding edge approach?

**Comment by eustas** [comment]
Hello, we plan to make a v1.0 release soon; not much changes compared to 0.1, just tiny fixes and speedups.

**Comment by uilianries** [comment]
@eustas thank you for your quick response!
