### ISSUE TITLE
WASM: error on image

### ISSUE THREAD

**Issue by Ser-Gen** [google/brunsli#30]
Win10, Chrome 76.0.3809.100 x64

image: https://drive.google.com/file/d/1N1tRXP45Fj_BgeB-qQnmuV3hl2X8gTxl/view?usp=sharing

```
brunslicodec-wasm.js:69 Uncaught abort(OOM). Build with -s ASSERTIONS=1 for more info.
```

  | z | @ | brunslicodec-wasm.js:69
-- | -- | -- | --
  | b | @ | brunslicodec-wasm.js:64
  | (anonymous) | @ | wasm-005ea102-70:1148
  | (anonymous) | @ | wasm-005ea102-226:11
  | (anonymous) | @ | wasm-005ea102-65:16
  | (anonymous) | @ | wasm-005ea102-1019:39
  | (anonymous) | @ | wasm-005ea102-534:18
  | (anonymous) | @ | wasm-005ea102-1023:46
  | (anonymous) | @ | wasm-005ea102-1026:84
  | (anonymous) | @ | wasm-005ea102-550:46
  | (anonymous) | @ | wasm-005ea102-552:20
  | (anonymous) | @ | wasm-005ea102-1083:402
  | (anonymous) | @ | wasm-005ea102-1076:386
  | (anonymous) | @ | wasm-005ea102-1056:157
  | (anonymous) | @ | wasm-005ea102-1492:79
  | e._JpegToBrunsli | @ | brunslicodec-wasm.js:65
  | processJpeg | @ | (index):207
  | reader.onload | @ | (index):155
  | load (async) |   |  
  | processNextFile | @ | (index):146
  | doProcessFiles | @ | (index):133
  | setTimeout (async) |   |  
  | processFiles | @ | (index):125
  | onFileSelect | @ | (index):115

**Comment by eustas** [comment]
WASM memory limit is set to 256 MiB. Will recompile on Monday with option that allows memory growth.
