### ISSUE TITLE
Tag stable release

### ISSUE THREAD

**Issue by EwoutH** [google/brunsli#50]
Many packages and integrators prefer or even require at least one release tagged to integrate a library, so that regressions don't impact them and to have a reliable source to download from. It would be nice if Brunsli could tag a (pre-)release as soon as possible, either 0.1 or 1.0, to accelerate adoption and thereby community involvement.

**Comment by eustas** [comment]
Done

**Comment by EwoutH** [comment]
Thanks for tagging the release! Could you upload the [build artifacts](https://ci.appveyor.com/project/EwoutH/brunsli/builds/28426876/artifacts) from AppVeyor to the [GitHub release page](https://github.com/google/brunsli/releases/tag/v0.1)?
