### ISSUE TITLE
Resolve Visual Studio compile warnings

### ISSUE THREAD

**Issue by EwoutH** [google/brunsli#51]
When compiling Brunsli with Visual Studio 2019 it currently throws [74 warnings](https://ci.appveyor.com/project/EwoutH/brunsli/build/messages).

**Comment by eustas** [comment]
Yep, will be working on that...

**Comment by eustas** [comment]
Now we have Appveyor integration -- bug warning fixing will become easier =)

**Comment by eustas** [comment]
Recent CI build sees none =)
