### ISSUE TITLE
Featrure: PNG and other common lossless format support

### ISSUE THREAD

**Issue by DonaldTsang** [google/brunsli#58]
Here is a list that I would like to see implemented.
It can be either Image => BMP/PNG intermediate => JXL or Image => direct to JXL
- [ ] BMP
- [ ] PNG
- [ ] WebP
- [ ] BPG
- [ ] HEIF (HEIC/AVCI)
- [ ] AVIF
- [ ] FLIF
- [ ] Other JPEG formats

**Comment by eustas** [comment]
Brunsli is a specialised repacker for quantized DCT coefficients from JPEG files.
Please consider JPEG XL codec for modern lossy/lossless image compression.

**Comment by DonaldTsang** [comment]
@eustas might sound repetitive but for reference please link the relevant repos.

**Comment by eustas** [comment]
JPEG XL reference implementation: https://gitlab.com/wg1/jpeg-xl
