### ISSUE TITLE
Feature: Animation support

### ISSUE THREAD

**Issue by DonaldTsang** [google/brunsli#59]
It might be possible to expand to animation formats
- [ ] GIF
- [ ] APNG
- [ ] HEIFS (HEICS/AVCS)
- [ ] FLIF
- [ ] WebP
- [ ] BPG
- [ ] AVIF

**Comment by eustas** [comment]
Brunsli is a specialised repacker for quantized DCT coefficients from JPEG files.
Please consider JPEG XL codec for animation, (pixel) lossless and modern lossy image compression.

**Comment by DonaldTsang** [comment]
@eustas mind if I ask, where are the repos for the codec in GitHub?

**Comment by eustas** [comment]
Sure. Not on GitHub, but on GitLab: https://gitlab.com/wg1/jpeg-xl

**Comment by DonaldTsang** [comment]
@eustas when will it be available on GitHub for open source purposes?

**Comment by eustas** [comment]
Not sure. Effectively, there is no difference between git hosts.
So the real question is - when the repo will be mirrored. But this question is better to be asked in JXL issue board =)
