### ISSUE TITLE
win build pls

### ISSUE THREAD

**Issue by necros2k7** [google/brunsli#62]
subj

**Comment by eustas** [comment]
Now we have Appveyor integration, so we could to a release soon with windows artefacts attached =)

**Comment by necros2k7** [comment]
appveyor link gives - Project not found or access denied. -

**Comment by eustas** [comment]
Will check / fix soon. Thanks for the heads-up.

**Comment by necros2k7** [comment]
August no build yet... (

**Comment by eustas** [comment]
Github Actions has windows build. And that one should upload artefacts.
Going to insert link / how-to in readme soon.
