### ISSUE TITLE
Brunsli cannot decode JPEG that was compressed in JPEG XL's reference software's unofficial build

### ISSUE THREAD

**Issue by Mithgol** [google/brunsli#90]
Looks like an interoperability problem. Steps to reproduce:

**Step 1.** We'll use the following picture of the [“Dude! Let Me In! I'm A Fairy!”](https://knowyourmeme.com/photos/72839-dude-let-me-in-im-a-fairy) meme:

![(“Dude! Let Me In! I'm A Fairy!”)](https://user-images.githubusercontent.com/1088720/83215799-76d06780-a170-11ea-9060-08ddc9404384.jpg)

**Step 2.** When I drag-and-drop the meme at https://google.github.io/brunsli/ to the transcoder, the following JPEG XL file is created:

[(ZIP archive of Brunsli's JXL file)](https://github.com/google/brunsli/files/4699446/Dude.Let.me.in.I.m.a.fairy.Brunsli.JXL.zip)

When I drag the JPEG XL file back to the transcoder, the returned JPEG file is byte-by-byte equivalent of the original (step 1), I can confirm it using `fc /b original.jpg decoded.jpg` on Windows.

**Step 3.** This time I'll try to repeat step 2 using [JPEG XL's reference software](https://gitlab.com/wg1/jpeg-xl/). I do not build it myself; I'll use an unofficial build (for Windows) distributed by user Jamaika [on Doom9 forum](https://forum.doom9.org/showthread.php?p=1913752#post1913752); that build is originally hosted [on sendspace.com,](https://www.sendspace.com/file/mno3fr) but here's a backup copy:

[(ZIP archive of Jamaika's build of JPEG XL's reference software)](https://github.com/google/brunsli/files/4699283/jpegXL_26052020.zip)

When I run `cjpegxl_jxl --version` it reports `version 0.0.1-6334944f` (seems to correspond to the latest commit in the public repo of JPEG XL's reference software).

When I run `cjpegXL_jxl -s 9` on the original JPEG file on Windows, the following JPEG XL is created:

[(ZIP archive of JXL file generated by Jamaika's build)](https://github.com/google/brunsli/files/4699457/Dude.Let.me.in.I.m.a.fairy.Jamaika.JXL.zip)

When I run `djpegXL_jxl --jpeg` on this result, the following JPEG file is decoded:

![(step 3 decoded meme)](https://user-images.githubusercontent.com/1088720/83216267-8603e500-a171-11ea-8577-ba5895989ed5.jpg)

Its size (84 836 bytes) is larger than original's (80 496 bytes) and it lacks all of the Exif metadata of the original JPEG. However, ImageMagick's comparison `magick compare -metric ae original.jpg decoded.jpg nul` reports that these files are equal pixel-by-pixel, though not byte-by-byte.

**Step 4.** When I drag-and-drop the JPEG XL file from step 3 (generated by Jamaika's build) at https://google.github.io/brunsli/ to the transcoder, the following error appears:

![(screenshot)](https://user-images.githubusercontent.com/1088720/83216587-4a1d4f80-a172-11ea-9f30-3df8316f70ba.png)

Brunsli cannot decode the JPEG file that was compressed in JPEG XL's reference software's unofficial build.

**Step 5.** Vice versa, when I use Jamaika's build's `djpegXL_jxl --jpeg` on Brunsli's JPEG XL file (from step 2), the following JPEG file is decoded:

![(Brunsli's JPEG XL file decoded by Jamaika's build)](https://user-images.githubusercontent.com/1088720/83216696-8e105480-a172-11ea-89fe-6115a4eb7368.jpg)

It has the same number of bytes (84 836 bytes) that Jamaika's build's decoded from its own JPEG XL (step 3), but much worse quality.

The above steps were performed in Windows 7 Professional 64-bit (Service Pack 1) running on Intel Core i7-3770 CPU.

The results may indicate that Jamaika's build is built incorrectly.

The results may also indicate that JPEG XL's reference software's authors tried to fix their own version of #80 but failed (the decoded JPEG file started to retain only pixel-by-pixel compatibility instead of its former byte-by-byte, but what's the point if the decoded file becomes larger, and lacks metadata, and does not have full interoperability with https://google.github.io/brunsli/ then).

Would someone kindly make their own build of JPEG XL's reference software and check what's really going on?

**Comment by eustas** [comment]
JPEG XL specification is an umbrella for several codecs and "containers".
"Brunsli" is just one on codecs. That is why it can not decode all the JPEG XL files.

Quality degradation is something new. Going to investigate that on the next week.

**Comment by eustas** [comment]
Just checked with freshly build binaries on OSX: indeed, `--jpeg` option causes degradation. I believe it is misleading; at least it should have better explanation what is does.
Currently there is no way to ask JXL CLI to restore original JPEG. There is, though, a "to-do" to add that ability.

BTW: one of JPEG XL CLI tools - `cbrunsli` - could be used to produce files compatible with https://brunsli.dev page. Unfortunately it is not included in Jamaicas build.

**Comment by Mithgol** [comment]
Brunsli encoder has a separate CLI and Brunsli decoder is not (yet) included in JXL CLI.

It makes sense, and thus the issue's closed.
