### ISSUE TITLE
What is the public API that should be exported?

### ISSUE THREAD

**Issue by hmaarrfk** [google/brunsli#93]
On windows, dll require the API to be explicitly exported.

Could you please specify which headers should be public and exported?

Thanks!

**Comment by eustas** [comment]
Hello. Just recently we've added what we perceive as final decoder API. Soon the will take care of exported symbols and publish doxygen-generated API reference.
For dynamic library we plan to have only C API, and preview of it is available in `c/include/brunsli/{de|en}code.h`
