### ISSUE TITLE
Encoding is 10x slower with Safari

### ISSUE THREAD

**Issue by jackyhallyday** [google/brunsli#94]
Hi,

Safari supports WASM, but the encoding speed is 10x slower with it (v13.1.1 or Technology Preview 109) than it is with Chrome or Firefox (https://google.github.io/brunsli/).
Is there something you can do to achieve similar performances across browsers?

**Comment by eustas** [comment]
I was asking WASM developers the similar questions... Got no answers.

As for Safari - I believe they use some kind of interpreter first... So try to encode few small images first, and then start real encoding. Should help.

**Comment by jackyhallyday** [comment]
Thanks for the tip, it works!
